#pragma once
#include "CoreMinimal.h"
#include "EBlamGameSkulls.generated.h"

UENUM(BlueprintType)
enum class EBlamGameSkulls : uint8 {
    Iron,
    BlackEye,
    ToughLuck,
    Catch,
    Fog,
    Famine,
    Thunderstorm,
    Tilt,
    Mythic,
    Assassin,
    Blind,
    Cowbell,
    GruntBirthdayParty,
    IWHBYD,
    CustomRed,
    CustomYellow,
    CustomBlue,
    Angry,
    Bandana,
    BondedPair,
    Boom,
    Envy,
    EyePatch,
    Foreign,
    Ghost,
    GruntFuneral,
    Jacked,
    Malfunction,
    Masterblaster,
    Pinata,
    Recession,
    Scarab,
    SoAngry,
    Swarm,
    ThatsJustWrong,
    TheyComeBack,
    BootsOffTheGround,
    Adaptation,
    Reload,
    SporeVisibility,
    NightVision,
    LightsOut,
    Riskrun,
    Pop,
    Armistice,
    EnduranceSpec,
    GiveAndTake,
    StowAndGrow,
    HipFire,
    Temperamental,
    FloorIsLava,
    Magnified,
    JohnnyAmmoTree,
    Leadhead,
    Efficient,
    ThirdPerson,
    Num,
    None = 255,
};

