#pragma once
#include "CoreMinimal.h"
#include "EBlamFirstPersonWeaponState.generated.h"

UENUM(BlueprintType)
enum class EBlamFirstPersonWeaponState : uint8 {
    Idle,
    IdleDualLeft,
    Ready,
    ReadyInitial,
    ReadyOverheated,
    ReloadWhileEmpty,
    ReloadWhileFull,
    ReloadContinuousEnter,
    ReloadContinuousWhileEmpty,
    ReloadContinuousWhileFull,
    ReloadContinuousExit,
    Chambering,
    Overheating,
    Overheated,
    OverheatedExit,
    VentEnter,
    VentLoop,
    VentExit,
    Overcharged,
    PrimaryFire,
    SecondaryFire,
    PrimaryMisfire,
    SecondaryMisfire,
    PutAway,
    ThrowGrenade,
    ThrowGrenadeOverheated,
    ThrowGrenadeVent,
    ThrowEquipment,
    Melee,
    MeleeFirstHit,
    MeleeFirstHitIdle,
    MeleeSecondHit,
    MeleeSecondHitIdle,
    MeleeThirdHit,
    MeleeStrike1,
    MeleeStrike2,
    MeleeStrike3,
    MeleeStrike4,
    MeleeDash,
    MeleeLunge,
    MeleeDashAirborne,
    MeleeLungeAirborne,
    MeleeLungeUnaimed,
    MeleeLungeUnaimedAirborne,
    MeleeClang,
    MeleeStrikeOverheated,
    MeleeStrikeVent,
    SprintEnter,
    SprintLoop,
    SprintLoopAirborne,
    SprintExit,
    LightOn,
    LightOff,
    Posing,
    UseHealthStation,
    Num,
    None = 255,
};

