#pragma once
#include "CoreMinimal.h"
#include "EBlamMotorTask.generated.h"

UENUM(BlueprintType)
enum class EBlamMotorTask : uint8 {
    Default,
    Jump,
    Stun,
    Accelerate,
    Dash,
    NotifyPhysicsBuilt,
    HandleSimulationWarp,
    ForceAirborne,
    ForceRelaxationState,
    ForceHeavy,
    Board,
    Ejection,
    Takeoff,
    Perch,
    Land,
    Attach,
    Detach,
    BunkerOpen,
    BunkerClose,
    Melee,
    Resurrect,
    GetInfected,
    Infect,
    DeathProgram,
    Clamber,
    Open,
    Close,
    Flip,
    VehicleAnimatedTrick,
    UnitEnter,
    WeaponAnimation,
    WeaponStow,
    WeaponDraw,
    Grenade,
    Equipment,
    Exit,
    Ping,
    Die,
    Animation,
    Posture,
    TransientPosture,
    Hoist,
    PlayAnimation,
    StopAnimation,
    LeapAnticipation,
    Leap,
    LeapRecovery,
    Surge,
    Phase,
    SyncAnimation,
    AnimatedJump,
    Num,
};

